### ISSUE TITLE
Question: format of the map?

### ISSUE THREAD

**Issue by apallier** [shannonturner/metro-map-maker#22]
Hi,
I would like to programmatically create a map and generate the image offline.
Do you think it's possible?
I know Python but not Django and I have difficulty to found where the map format is implemented.
Any guidance?
Thanks

**Comment by MiniAlfa** [comment]
@apallier  The implementation is in html and js, so just filter on those languages.

you can find the implementation at metro_map_saver/map_saver/static/js/metromapmaker.js

**Comment by shannonturner** [comment]
Heads up that the data version has changed pretty significantly in v6 (data version 2): https://github.com/shannonturner/metro-map-maker/releases/tag/v6.0

The main changes are that points are now grouped by color, styles have been added, and stations are in their own section separate from the lines. See https://www.youtube.com/watch?v=OErGHMzAekw for general information about the new release.

It may interest you to know that the latest version also generates images in SVG format from your maps, so that's another format that's usable here in case that's useful for your purposes.

Happy mapmaking!

**Comment by apallier** [comment]
Hi @shannonturner, thank you for your reply. Metro-Map-Maker is a nice project!
The SVG format is actually an interesting new feature.

For now, I've abandoned the idea of generating a map programmatically, but I've discovered that the format can be easily found in the browser's local storage :)

**Comment by shannonturner** [comment]
So glad you like it!

Generating a map programmatically might be pretty challenging. I've thought about it a few different ways when thinking of how I might automatically create a remixable map in Metro Map Maker from the "official" metro system maps around the world, but haven't really spent much time on it.

Happy map making, I hope you like the new version!
