### ISSUE TITLE
Can't input Chinese

### ISSUE THREAD

**Issue by misaka00251** [shannonturner/metro-map-maker#9]
Only English supported?

**Comment by shannonturner** [comment]
For now, only A-Z and 0-9 are available to name your stations due to a technical design limitation in an earlier version. It's possible to expand the available characters now to also allow Chinese and other characters, but that isn't in place at this time.

Rail lines, however, fully support Chinese and other characters. Happy mapmaking!

**Comment by shannonturner** [comment]
Fixed in 82ad478, which adds support for Chinese characters in station names as well as things like ♿️ to indicate station accessibility. Thank you for opening this issue and happy map making!
